version: '3.8'

services:
  radarr-manager:
    image: ghcr.io/leof28/radarr-manager:latest
    container_name: radarr-manager
    ports:
      - "5550:5000"
    volumes:
      # IMPORTANT: Mount the common root to allow hardlinks (same filesystem)
      - ${MEDIA_PATH}:/media
      # Persistent configuration and SQLite database
      - ${APP_PATH}/config:/app/config
    environment:
      - RADARR_URL=${NAS_IP}:7878
      - API_KEY=${RADARR_API}
      - SOURCE_ROOT=/media/movies/A trier
      - MEDIA_ROOT=/media/movies
      - OWNER_USER=${UID}  # Your NAS user UID (run: id -u)
      - OWNER_GROUP=${GID} # Your NAS group GID (run: id -g)
      - TZ=Europe/Paris  # Your timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
